// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTQX2H3QJHUbtKWGp6g4Prc3NpPe9Yke0',
    appId: '1:1001842594968:web:7960c99909070b2db0eced',
    messagingSenderId: '1001842594968',
    projectId: 'my-baby-tracker-app24',
    authDomain: 'my-baby-tracker-app24.firebaseapp.com',
    storageBucket: 'my-baby-tracker-app24.appspot.com',
    measurementId: 'G-2PPYC4BBKL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDeibkJar0-ZLgSY2NYNSHPKCB7Ak7uGE',
    appId: '1:1001842594968:android:dce84f1e2cd8d925b0eced',
    messagingSenderId: '1001842594968',
    projectId: 'my-baby-tracker-app24',
    storageBucket: 'my-baby-tracker-app24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD36ZjXSV6_0ZmXuteseO0CmKSJbawoQE',
    appId: '1:1001842594968:ios:7a38c338c0140f42b0eced',
    messagingSenderId: '1001842594968',
    projectId: 'my-baby-tracker-app24',
    storageBucket: 'my-baby-tracker-app24.appspot.com',
    iosBundleId: 'com.example.babyTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBD36ZjXSV6_0ZmXuteseO0CmKSJbawoQE',
    appId: '1:1001842594968:ios:a51f1f9170803c80b0eced',
    messagingSenderId: '1001842594968',
    projectId: 'my-baby-tracker-app24',
    storageBucket: 'my-baby-tracker-app24.appspot.com',
    iosBundleId: 'com.example.babyTrackerApp.RunnerTests',
  );
}
