/// Flutter icons Baby
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Baby
///      fonts:
///       - asset: fonts/Baby.ttf
///
///
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class Baby {
  Baby._();

  static const _kFontFam = 'Baby';
  static const String? _kFontPkg = null;

  static const IconData phone = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData termOfUse = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData restore = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData feed = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sleep = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData premium = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rate = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData privacy = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData date = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData symptoms = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tick = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xf133, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
